controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /api/login
    methods: ['POST']

signin:
    path: /api/signin
    methods: ['POST']
    defaults:
        _controller: App\Controller\SignInController::__invoke
        _api_resource_class: App\Entity\User

# signup:
#     path: /api/signup
#     methods: ['POST']